server:
  port: 8089
  servlet:
    context-path: /rest/v1.0/springcloud

spring:
  application:
    name: msvc-cursos
  datasource:
    url: jdbc:postgresql://localhost:5432/msvc_cursos
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create  # Asegúrate de usar 'ddl-auto' en lugar de 'dll-auto'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org.hibernate.SQL: debug
