server:
  port: 8088
  servlet:
    context-path: /rest/v1.0/springcloud

spring:
  application:
    name: msvc-usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/msvc_usuarios
    username: root
    password: root
    driverClassName: com.mysql.cj.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      show_sql: true
      hbm2dll:
        auto: true
  jpa:
    show-sql: true
    hibernate:
      dll-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
loggin:
  level:
    org.hibernate.SQL: debug