server:
  port: 8088
  servlet:
    context-path: /rest/v1.0/springcloud

spring:
  application:
    name: msvc-usuarios
  datasource:
    url: jdbc:mysql://localhost:3306/msvc_usuarios
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create  # Asegúrate de usar 'ddl-auto' en lugar de 'dll-auto'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.hibernate.SQL: debug
